title: Duncan Mearns
email: dm3169@princeton.edu
description: >-
  Personal website
baseurl: ""
url: "http://duncanmearns.github.io"
twitter_username: duncan_mearns
github_username:  DuncanMearns
theme: minima
