# Site settings
title: "Duncan Mearns"
description: "Behavior - Circuits - Evolution - Music"
url: "http://duncanmearns.github.io"
baseurl: ""

include:
  - _pages

# Collections
collections_dir: collections
collections:
  research:
    output: false
  code:
    output: false
  music:
    output: false