# Site settings
title: "Duncan Mearns"
description: "Behavior - Circuits - Evolution - Music"
url: ""  # http://duncanmearns.github.io
baseurl: ""

include:
  - _pages

# Collections
collections_dir: collections
collections:
  music:
    output: false
    order:
      - piano.md
      - composition.md
  code:
    output: false
    order:
      - ethomap.md
      - pydra.md
      - website.md
  research:
    output: false
    order:
      - ethology.md
      - evolution.md
      - circuits.md