social:
  twitter: {icon: 'twitter', prefix: 'fab fa', link: 'https://twitter.com/duncan_mearns'}
  scholar: {icon: 'google-scholar', prefix: 'ai ai', link: 'https://scholar.google.com/citations?user=kgB3M1EAAAAJ&hl=en'}
  orcid: {icon: 'orcid', prefix: 'fab fa', link: 'https://orcid.org/0000-0002-3817-1919'}
  github: {icon: 'github', prefix: 'fab fa', link: 'https://github.com/DuncanMearns'}
  instagram: {icon: 'instagram', prefix: 'fab fa', link: 'https://instagram.com/drdrunkin'}

contact:
  name: 'Duncan Mearns, PhD'
  title: 'Associate Research Scholar'
  institution: 'Princeton Neuroscience Institute'
  institution_url: 'https://pni.princeton.edu/'
  address1: 'Washington Road'
  address2: 'Princeton, NJ 08544'
  phone: 'TBD'
  email: 'dm3169@princeton.edu'
  office: 'A92H PNI'
  image: 'assets/img/mugshot.jpg'

music:
- {title: 'Impromptu No. 1', url: '/files/music/impromptu_no_1.pdf', instrument: 'Piano Solo', year: '2019', description: ''}
- {title: 'Alone', url: '/files/music/alone.pdf', instrument: 'Piano Solo', year: '2020', description: 'prelude written during the COVID19 pandemic'}
- {title: 'Ballade No. 1', url: '/files/music/ballade_no_1.pdf', instrument: 'Piano Solo', year: '2020', description: 'written during the pandemic'}
- {title: 'Spider Fugue', url: '/files/music/spider_fugue.pdf', instrument: 'Piano Solo', year: '2021', description: 'my first attempt at a fugue'}
- {title: 'Wave Function Collapse', url: '/files/music/wave_function_collapse.pdf', instrument: 'Cello & Piano', year: '2022', description: 'written for M.A.K.'}

music-early:
- {title: 'Waltz in C Minor', url: '/music/c_minor_waltz.pdf', instrument: 'Piano Solo', year: '~2008', description: 'my first composition'}
- {title: 'Nocturne in F Minor', url: '/music/nocturne.pdf', instrument: 'Piano Solo', year: '~2010?', description: ''}