menu:
- {name: 'Research', url: '/pages/research'}
- {name: 'Publications', url: '/pages/publications'}
- {name: 'Code', url: '/pages/code'}
- {name: 'CV', url: '/pages/cv'}
- {name: 'Music', url: '/pages/music'}
- {name: 'Contact', url: '/pages/contact'}

social:
  twitter: {icon: 'twitter', link: 'https://twitter.com/duncan_mearns'}
  scholar: {icon: 'mortar-board', link: 'https://scholar.google.com/citations?user=kgB3M1EAAAAJ&hl=en'}
  orcid: {icon: 'orcid', link: 'https://orcid.org/0000-0002-3817-1919'}
  github: {icon: 'github', link: 'https://github.com/DuncanMearns'}
  instagram: {icon: 'instagram', link: 'https://instagram.com/drdrunkin'}

contact:
  name: 'Duncan Mearns, PhD'
  title: 'Associate Research Scholar'
  institution: 'Princeton Neuroscience Institute'
  institution_url: 'https://pni.princeton.edu/'
  address1: 'Washington Road'
  address2: 'Princeton, NJ 08544'
  phone: 'TBD'
  email: 'dm3169@princeton.edu'
  office: 'A92H PNI'
  image: 'assets/img/mugshot.jpg'

music:
- {title: 'Impromptu No. 1', url: '/music/impromptu_no_1.pdf', instrument: 'Piano Solo', year: '2019', description: ''}
- {title: 'Alone', url: '/music/alone.pdf', instrument: 'Piano Solo', year: '2020', description: 'prelude written during the COVID19 pandemic'}
- {title: 'Ballade No. 1', url: '/music/ballade_no_1.pdf', instrument: 'Piano Solo', year: '2020', description: 'written during the pandemic'}
- {title: 'Spider Fugue', url: '/music/spider_fugue.pdf', instrument: 'Piano Solo', year: '2021', description: 'my first attempt at a fugue'}
- {title: 'Wave Function Collapse', url: '/music/wave_function_collapse.pdf', instrument: 'Cello & Piano', year: '2022', description: 'written for M.A.K.'}

music-early:
- {title: 'Waltz in C Minor', url: '/music/c_minor_waltz.pdf', instrument: 'Piano Solo', year: '~2008', description: 'my first composition'}
- {title: 'Nocturne in F Minor', url: '/music/nocturne.pdf', instrument: 'Piano Solo', year: '~2010?', description: ''}

code-repositories:
  - {title: 'Ethomap', repo: 'ethomap', description: 'Description goes here'}
  - {title: 'Pydra', repo: 'pydra', description: 'Lorem ipsum'}
  - {title: 'This site', repo: 'DuncanMearns.github.io', description: 
  'I built this site using Jekyll using  
  <a href="https://lenpaul.github.io/academic/" target="_blank">this theme</a>
  as a template.'}
