menu:
- {name: 'Research', url: '/pages/research'}
- {name: 'Publications', url: '/pages/publications'}
- {name: 'Code', url: '/pages/code'}
- {name: 'CV', url: '/pages/cv'}
- {name: 'Music', url: '/pages/music'}
- {name: 'Contact', url: '/pages/contact'}

social:
- {icon: 'twitter', link: 'https://twitter.com/duncan_mearns'}
- {icon: 'github', link: 'https://github.com/DuncanMearns'}
- {icon: 'instagram', link: 'https://instagram.com/drdrunkin'}

contact:
- name: 'Duncan Mearns, PhD'
  title: 'Associate Research Scholar'
  institution: 'Princeton Neuroscience Institute'
  institution_url: 'https://pni.princeton.edu/'
  address1: 'Washington Road'
  address2: 'Princeton, NJ 08544'
  phone: 'TBD'
  email: 'dm3169@princeton.edu'
  office: 'A92H PNI'
  image: 'assets/img/mugshot.jpg'

music:
- {title: 'Ballade No. 1', url: '/music/ballade_no_1.pdf', instrument: 'Piano Solo', year: '2019', description: ''}
- {title: 'Alone', url: '/music/alone.pdf', instrument: 'Piano Solo', year: '2020', description: 'impromptu written during the COVID19 pandemic'}
- {title: 'Ballade No. 2', url: '', instrument: 'Piano Solo', year: '2020', description: 'also written during the pandemic'}
- {title: 'Spider Fugue', url: '', instrument: 'Piano Solo', year: '2021', description: 'my first attempt at a fugue'}
- {title: 'Wave Function Collapse', url: '', instrument: 'Cello & Piano', year: '2022', description: 'written for M.A.K.'}
